= Eric Wood
<ejwood@gmail.com>

[quote]
Building and operating large-scale systems

link:mailto:ejwood@gmail.com[ejwood@gmail.com]

https://github.com/ejwood79/resume

=== Profile

Leader with a proven track record of building teams and systems that support hundreds of millions of users.

=== Most Familiar Technologies

[grid="none"]
|======
|Java/Java EE | Spring, Spring Boot, Spring Social | JPA/Hibernate
|Scala | Kafka | Zipkin
|OpenID Connect | OAuth | SAML
|Redis | Postgres | DynamoDB
|AWS | New Relic | Pagerduty
|JIRA | Confluence | Slack
|======

=== Experience

==== Under Armour Connected Fitness
*Senior Manager, Foundation Services* +
_February 2015 - Present_

* Collaborate with product and other engineering teams to define services critical to Under Armour's Connected Fitness
  vision.
* Define and execute the product roadmap to make interacting with complex distributed systems simple and fast.
* Lead build vs. buy decisions for each service.
* Review effectiveness of services with greater engineering team through surveys and interviews.
* Build a team from zero to over 15 reports.
* Co-chair, UA Unified: Under Armour's LGTBQ diversity club.

==== IBM
*Global Leader, Cloud Identity Services Solution Design* +
_August 2014-January 2015_

Lead a worldwide team of Solution Architects in presales activities for IBM's Cloud Identity Services offering
(formerly Lighthouse Security Gateway). Perform customer demos, gather requirements and scope, and design technical
solutions to customer identity and access management scenarios across multiple industries and regulatory environments.
Responsible for solution architecture, sizing, pricing, and approval of contracts issued to customers.
Through customer interaction, influence the product roadmap. Gain insight into competitive offerings and work with
product management to plan new features.

==== Lighthouse Security Gateway
*Principal Cloud Security Architect, Delivery Lead* +
_October 2011 - August 2014_

Lead customer on-ramp engagements to deploy identity and access management services in a private cloud built with the
IBM Security portfolio. Project sizing, requirements generation, solution design, and customer communication. Lead
teams of engineers to deploy services, including hands-on custom development and project implementation where required.
Use project experiences to help prioritize the product roadmap. Contribute to product development efforts when time
allows or projects require. Introduce transformative tools and technologies company-wide, including Redis, Spring Boot,
JIRA, JIRA Agile, Confluence, HipChat, Gradle, and New Relic.

==== International Business Machines (IBM)
*Senior Managing Consultant, Security and Privacy Practice* +
_May 2010-October 2011_

Responsible for Security Architecture, requirements definition, project implementation, customer presentation and
communication across a number of engagements in different industries.

*Chief Programmer, IBM Security Policy Manager* +
_2006 - May 2010_

Led the organization's first large global agile team (40+) of developers, testers, and writers, with a multi-million
dollar budget, to develop the first version of IBM Security Policy Manager. Worked with technical leadership to both
set and deliver on technical strategy for security policy management and enforcement. Led first PoCs and initial
deployments for customers. Worked with upper management and cross-functional teams to introduce Agile and Scrum
methodologies into our development process. Technologies included EJBs, WS-* Web Services, Dojo, and ORM.
Served as a Lab Advocate for several customers, responsible for articulating roadmaps and strategy, ensuring customers’
issues are addressed in the product, and ensuring customer satisfaction.

*Software Engineer, IBM Security Federated Identity Manager* +
_2004-2006_

Worked with customers using interaction design methodologies to gather requirements, and improve usability. Designed,
developed, and tested several components across the presentation and business logic tiers of the product. Developed
using Rational and Eclipse-based tools in a J2EE environment using portlets, servlets, EJBs, XML processing, and web
services.

*Software Engineer, IBM Security Access Manager*
_2003-2004_

Responsible for the design, development, and test of several modules of the C/C++ web proxy component. Worked as a
level 3 support liaison to fix customer-reported defects that our support team could not, and worked directly with
those customers to ensure their defects were fixed.

=== Education

*California Polytechnic State University, San Luis Obispo* +
B.S., M.S. (with distinction), Computer Science, Business minor +
_1997 - 2003_